<?php

declare(strict_types=1);

namespace TrackTelemetry\Traccar\Dto;

class UserAttributesData
{
    public function __construct(
        public ?string $language = null,
        public bool $mapGeofences = false,
        public ?string $mapLiveRoutes = null,
        public ?string $mapDirection = null,
        public bool $mapFollow = false,
        public bool $mapCluster = false,
        public bool $mapOnSelect = false,
        public ?string $activeMapStyles = null,
        public ?string $devicePrimary = null,
        public ?string $deviceSecondary = null,
        public ?string $soundEvents = null,
        public ?string $soundAlarms = null,
        public ?string $positionItems = null,
        public ?string $googleKey = null,
        public ?string $locationIqKey = null,
        public ?string $mapboxAccessToken = null,
        public ?string $mapTilerKey = null,
        public ?string $bingMapsKey = null,
        public ?string $openWeatherKey = null,
        public ?string $tomTomKey = null,
        public ?string $hereKey = null,
        public ?string $notificationTokens = null,
        public bool $uiDisableSavedCommands = false,
        public bool $uiDisableGroups = false,
        public bool $uiDisableAttributes = false,
        public bool $uiDisableEvents = false,
        public bool $uiDisableVehicleFeatures = false,
        public bool $uiDisableDrivers = false,
        public bool $uiDisableComputedAttributes = false,
        public bool $uiDisableCalendars = false,
        public bool $uiDisableMaintenance = false,
        public ?int $webLiveRouteLength = null,
        public ?float $mapLineWidth = null,
        public ?float $mapLineOpacity = null,
        public ?int $webSelectZoom = null,
        public ?int $webMaxZoom = null,
        public ?float $iconScale = null,
        public ?string $navigationAppLink = null,
        public ?string $navigationAppTitle = null,
        public ?string $telegramChatId = null,
        public ?string $pushoverUserKey = null,
        public ?string $pushoverDeviceNames = null,
        public ?string $mailSmtpHost = null,
        public ?int $mailSmtpPort = null,
        public bool $mailSmtpStarttlsEnable = false,
        public bool $mailSmtpStarttlsRequired = false,
        public bool $mailSmtpSslEnable = false,
        public ?string $mailSmtpSslTrust = null,
        public ?string $mailSmtpSslProtocols = null,
        public ?string $mailSmtpFrom = null,
        public bool $mailSmtpAuth = false,
        public ?string $mailSmtpUsername = null,
        public ?string $mailSmtpPassword = null,
        public bool $termsAccepted = false,
        public ?string $billingLink = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            language: $data['language'] ?? null,
            mapGeofences: (bool) ($data['mapGeofences'] ?? false),
            mapLiveRoutes: $data['mapLiveRoutes'] ?? null,
            mapDirection: $data['mapDirection'] ?? null,
            mapFollow: (bool) ($data['mapFollow'] ?? false),
            mapCluster: (bool) ($data['mapCluster'] ?? false),
            mapOnSelect: (bool) ($data['mapOnSelect'] ?? false),
            activeMapStyles: $data['activeMapStyles'] ?? null,
            devicePrimary: $data['devicePrimary'] ?? null,
            deviceSecondary: $data['deviceSecondary'] ?? null,
            soundEvents: $data['soundEvents'] ?? null,
            soundAlarms: $data['soundAlarms'] ?? null,
            positionItems: $data['positionItems'] ?? null,
            googleKey: $data['googleKey'] ?? null,
            locationIqKey: $data['locationIqKey'] ?? null,
            mapboxAccessToken: $data['mapboxAccessToken'] ?? null,
            mapTilerKey: $data['mapTilerKey'] ?? null,
            bingMapsKey: $data['bingMapsKey'] ?? null,
            openWeatherKey: $data['openWeatherKey'] ?? null,
            tomTomKey: $data['tomTomKey'] ?? null,
            hereKey: $data['hereKey'] ?? null,
            notificationTokens: $data['notificationTokens'] ?? null,
            uiDisableSavedCommands: (bool) ($data['ui.disableSavedCommands'] ?? false),
            uiDisableGroups: (bool) ($data['ui.disableGroups'] ?? false),
            uiDisableAttributes: (bool) ($data['ui.disableAttributes'] ?? false),
            uiDisableEvents: (bool) ($data['ui.disableEvents'] ?? false),
            uiDisableVehicleFeatures: (bool) ($data['ui.disableVehicleFeatures'] ?? false),
            uiDisableDrivers: (bool) ($data['ui.disableDrivers'] ?? false),
            uiDisableComputedAttributes: (bool) ($data['ui.disableComputedAttributes'] ?? false),
            uiDisableCalendars: (bool) ($data['ui.disableCalendars'] ?? false),
            uiDisableMaintenance: (bool) ($data['ui.disableMaintenance'] ?? false),
            webLiveRouteLength: isset($data['web.liveRouteLength']) ? (int) $data['web.liveRouteLength'] : null,
            mapLineWidth: isset($data['mapLineWidth']) ? (float) $data['mapLineWidth'] : null,
            mapLineOpacity: isset($data['mapLineOpacity']) ? (float) $data['mapLineOpacity'] : null,
            webSelectZoom: isset($data['web.selectZoom']) ? (int) $data['web.selectZoom'] : null,
            webMaxZoom: isset($data['web.maxZoom']) ? (int) $data['web.maxZoom'] : null,
            iconScale: isset($data['iconScale']) ? (float) $data['iconScale'] : null,
            navigationAppLink: $data['navigationAppLink'] ?? null,
            navigationAppTitle: $data['navigationAppTitle'] ?? null,
            telegramChatId: $data['telegramChatId'] ?? null,
            pushoverUserKey: $data['pushoverUserKey'] ?? null,
            pushoverDeviceNames: $data['pushoverDeviceNames'] ?? null,
            mailSmtpHost: $data['mail.smtp.host'] ?? null,
            mailSmtpPort: isset($data['mail.smtp.port']) ? (int) $data['mail.smtp.port'] : null,
            mailSmtpStarttlsEnable: (bool) ($data['mail.smtp.starttls.enable'] ?? false),
            mailSmtpStarttlsRequired: (bool) ($data['mail.smtp.starttls.required'] ?? false),
            mailSmtpSslEnable: (bool) ($data['mail.smtp.ssl.enable'] ?? false),
            mailSmtpSslTrust: $data['mail.smtp.ssl.trust'] ?? null,
            mailSmtpSslProtocols: $data['mail.smtp.ssl.protocols'] ?? null,
            mailSmtpFrom: $data['mail.smtp.from'] ?? null,
            mailSmtpAuth: (bool) ($data['mail.smtp.auth'] ?? false),
            mailSmtpUsername: $data['mail.smtp.username'] ?? null,
            mailSmtpPassword: $data['mail.smtp.password'] ?? null,
            termsAccepted: (bool) ($data['termsAccepted'] ?? false),
            billingLink: $data['billingLink'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'language'                     => $this->language,
            'mapGeofences'                 => $this->mapGeofences,
            'mapLiveRoutes'                => $this->mapLiveRoutes,
            'mapDirection'                 => $this->mapDirection,
            'mapFollow'                    => $this->mapFollow,
            'mapCluster'                   => $this->mapCluster,
            'mapOnSelect'                  => $this->mapOnSelect,
            'activeMapStyles'              => $this->activeMapStyles,
            'devicePrimary'                => $this->devicePrimary,
            'deviceSecondary'              => $this->deviceSecondary,
            'soundEvents'                  => $this->soundEvents,
            'soundAlarms'                  => $this->soundAlarms,
            'positionItems'                => $this->positionItems,
            'googleKey'                    => $this->googleKey,
            'locationIqKey'                => $this->locationIqKey,
            'mapboxAccessToken'            => $this->mapboxAccessToken,
            'mapTilerKey'                  => $this->mapTilerKey,
            'bingMapsKey'                  => $this->bingMapsKey,
            'openWeatherKey'               => $this->openWeatherKey,
            'tomTomKey'                    => $this->tomTomKey,
            'hereKey'                      => $this->hereKey,
            'notificationTokens'           => $this->notificationTokens,
            'ui.disableSavedCommands'      => $this->uiDisableSavedCommands,
            'ui.disableGroups'             => $this->uiDisableGroups,
            'ui.disableAttributes'         => $this->uiDisableAttributes,
            'ui.disableEvents'             => $this->uiDisableEvents,
            'ui.disableVehicleFeatures'    => $this->uiDisableVehicleFeatures,
            'ui.disableDrivers'            => $this->uiDisableDrivers,
            'ui.disableComputedAttributes' => $this->uiDisableComputedAttributes,
            'ui.disableCalendars'          => $this->uiDisableCalendars,
            'ui.disableMaintenance'        => $this->uiDisableMaintenance,
            'web.liveRouteLength'          => $this->webLiveRouteLength,
            'mapLineWidth'                 => $this->mapLineWidth,
            'mapLineOpacity'               => $this->mapLineOpacity,
            'web.selectZoom'               => $this->webSelectZoom,
            'web.maxZoom'                  => $this->webMaxZoom,
            'iconScale'                    => $this->iconScale,
            'navigationAppLink'            => $this->navigationAppLink,
            'navigationAppTitle'           => $this->navigationAppTitle,
            'telegramChatId'               => $this->telegramChatId,
            'pushoverUserKey'              => $this->pushoverUserKey,
            'pushoverDeviceNames'          => $this->pushoverDeviceNames,
            'mail.smtp.host'               => $this->mailSmtpHost,
            'mail.smtp.port'               => $this->mailSmtpPort,
            'mail.smtp.starttls.enable'    => $this->mailSmtpStarttlsEnable,
            'mail.smtp.starttls.required'  => $this->mailSmtpStarttlsRequired,
            'mail.smtp.ssl.enable'         => $this->mailSmtpSslEnable,
            'mail.smtp.ssl.trust'          => $this->mailSmtpSslTrust,
            'mail.smtp.ssl.protocols'      => $this->mailSmtpSslProtocols,
            'mail.smtp.from'               => $this->mailSmtpFrom,
            'mail.smtp.auth'               => $this->mailSmtpAuth,
            'mail.smtp.username'           => $this->mailSmtpUsername,
            'mail.smtp.password'           => $this->mailSmtpPassword,
            'termsAccepted'                => $this->termsAccepted,
            'billingLink'                  => $this->billingLink,
        ];
    }
}
